### ISSUE TITLE
1 missing location in New Jersey in 1984

### ISSUE THREAD

**Issue by lukeave** [MappingtheGayGuides/mgg-website#40]
1 out of 90 locations in New Jersey in 1984 does not show up on the map.

**Comment by regan008** [comment]
The culprit here is a cruisy area that didn't get marked as unclear and google couldn't geocode. We need to identify lat/lon coords for the W. end of Boardwalk (#3418 in airtable). 

When you look for the coordinates, you might first check to see what coordinates we've used for this location in other years. Theres a good chance that we have already located it and just need to copy over the coordinates. Here's a geocoder you can use: https://developers-dot-devsite-v2-prod.appspot.com/maps/documentation/utils/geocoder/
